[package]
name = "actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.2.2"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
serde = "1.0"